import type { Problem } from '@/types';

export const DEMO_PROBLEMS: Omit<Problem, 'id'>[] = [
  {
    title: 'Two Sum',
    difficulty: 'Easy',
    tags: ['Arrays', 'Hash Maps'],
    leetcodeNumber: 1,
    url: 'https://leetcode.com/problems/two-sum/',
    status: 'Solved Independently',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    lastAttemptedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    notes: 'Use a hash map to store complement values. Time: O(n), Space: O(n)',
    solution: `function twoSum(nums, target) {\n  const map = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const complement = target - nums[i];\n    if (map.has(complement)) {\n      return [map.get(complement), i];\n    }\n    map.set(nums[i], i);\n  }\n  return [];\n}\n\nconsole.log(twoSum([2,7,11,15], 9));`,
  },
  {
    title: 'Valid Parentheses',
    difficulty: 'Easy',
    tags: ['Strings', 'Backtracking'],
    leetcodeNumber: 20,
    url: 'https://leetcode.com/problems/valid-parentheses/',
    status: 'Solved Independently',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    lastAttemptedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    notes: 'Use a stack. Push opening brackets, pop and check for closing brackets.',
    solution: `function isValid(s) {\n  const stack = [];\n  const map = { ')': '(', '}': '{', ']': '[' };\n  for (const char of s) {\n    if ('([{'.includes(char)) stack.push(char);\n    else if (stack.pop() !== map[char]) return false;\n  }\n  return stack.length === 0;\n}\n\nconsole.log(isValid("()[]{}"));`,
  },
  {
    title: 'Best Time to Buy and Sell Stock',
    difficulty: 'Easy',
    tags: ['Arrays', 'Sliding Window'],
    leetcodeNumber: 121,
    url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
    status: 'Solved with Help',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    lastAttemptedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    notes: 'Track minimum price seen so far and maximum profit possible.',
  },
  {
    title: 'Maximum Subarray',
    difficulty: 'Medium',
    tags: ['Arrays', 'Dynamic Programming'],
    leetcodeNumber: 53,
    url: 'https://leetcode.com/problems/maximum-subarray/',
    status: 'Solved with Help',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    lastAttemptedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    notes: "Kadane's algorithm - track current sum and reset when it goes negative.",
  },
  {
    title: 'Climbing Stairs',
    difficulty: 'Easy',
    tags: ['Dynamic Programming'],
    leetcodeNumber: 70,
    url: 'https://leetcode.com/problems/climbing-stairs/',
    status: 'Solved Independently',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    lastAttemptedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    notes: 'Classic fibonacci pattern. dp[n] = dp[n-1] + dp[n-2]',
    solution: `function climbStairs(n) {\n  if (n <= 2) return n;\n  let prev = 1, curr = 2;\n  for (let i = 3; i <= n; i++) {\n    [prev, curr] = [curr, prev + curr];\n  }\n  return curr;\n}\n\nconsole.log(climbStairs(10));`,
  },
  {
    title: 'Number of Islands',
    difficulty: 'Medium',
    tags: ['Graphs', 'Backtracking'],
    leetcodeNumber: 200,
    url: 'https://leetcode.com/problems/number-of-islands/',
    status: 'Attempted',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    lastAttemptedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    notes: 'DFS approach - mark visited cells, count connected components.',
  },
  {
    title: 'Longest Palindromic Substring',
    difficulty: 'Medium',
    tags: ['Strings', 'Dynamic Programming'],
    leetcodeNumber: 5,
    url: 'https://leetcode.com/problems/longest-palindromic-substring/',
    status: 'Not Attempted',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    lastAttemptedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Word Search',
    difficulty: 'Hard',
    tags: ['Backtracking', 'Graphs'],
    leetcodeNumber: 79,
    url: 'https://leetcode.com/problems/word-search/',
    status: 'Not Attempted',
    createdAt: new Date(),
    lastAttemptedAt: new Date(),
  },
];